services:
  - type: web
    name: posts-explorer-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: MONGO_URI
        generateValue: true
        scope: run
      - key: JWT_SECRET
        generateValue: true
        scope: run
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: PUBLIC_MEDIA_URL
        sync: false

deploy:
  id: posts-explorer-backend
  image:
    context: ./backend
